// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import * as WOS from "./wos";
import type { WaveEnv } from "@/app/waveenv/waveenv";

function callBackendService(waveEnv: WaveEnv, service: string, method: string, args: any[], noUIContext?: boolean): Promise<any> {
    if (waveEnv != null) {
        return waveEnv.callBackendService(service, method, args, noUIContext)
    }
    return WOS.callBackendService(service, method, args, noUIContext);
}

// aisessionsservice.AISessionsService (aisessions)
export class AISessionsServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // list AI session migration backups
    // @returns AI session backup stats
    BackupStats(request: AISessionsBackupRequest): Promise<BackupStats> {
        return callBackendService(this?.waveEnv, "aisessions", "BackupStats", Array.from(arguments))
    }

    // abort a running turn in a live chat session
    ChatAbort(request: AISessionsChatControlRequest): Promise<void> {
        return callBackendService(this?.waveEnv, "aisessions", "ChatAbort", Array.from(arguments))
    }

    // shut down a live chat session and its underlying subprocess
    ChatClose(request: AISessionsChatControlRequest): Promise<void> {
        return callBackendService(this?.waveEnv, "aisessions", "ChatClose", Array.from(arguments))
    }

    // delete old AI session migration backups
    // @returns AI session backup cleanup result
    CleanupBackups(request: AISessionsBackupRequest): Promise<BackupCleanupResult> {
        return callBackendService(this?.waveEnv, "aisessions", "CleanupBackups", Array.from(arguments))
    }

    // delete a local AI session by moving its source file to deleted storage
    // @returns deleted AI session summary
    Delete(id: string): Promise<SessionSummary> {
        return callBackendService(this?.waveEnv, "aisessions", "Delete", Array.from(arguments))
    }

    // load a local AI session detail
    // @returns AI session detail
    Detail(request: AISessionsDetailRequest): Promise<SessionDetail> {
        return callBackendService(this?.waveEnv, "aisessions", "Detail", Array.from(arguments))
    }

    // load newly appended AI session detail messages
    // @returns AI session message delta
    DetailDelta(request: AISessionsDetailDeltaRequest): Promise<MessageDelta> {
        return callBackendService(this?.waveEnv, "aisessions", "DetailDelta", Array.from(arguments))
    }

    // list local AI sessions
    // @returns AI session summaries
    List(request: AISessionsListRequest): Promise<AISessionsListResponse> {
        return callBackendService(this?.waveEnv, "aisessions", "List", Array.from(arguments))
    }

    // mark or unmark a local AI session
    // @returns updated AI session summary
    Mark(id: string, marked: boolean): Promise<SessionSummary> {
        return callBackendService(this?.waveEnv, "aisessions", "Mark", Array.from(arguments))
    }

    // set a local AI session note
    // @returns updated AI session summary
    Note(id: string, note: string): Promise<SessionSummary> {
        return callBackendService(this?.waveEnv, "aisessions", "Note", Array.from(arguments))
    }

    // set a local AI session note and tags
    // @returns updated AI session summary
    NoteAndTags(request: AISessionsNoteAndTagsRequest): Promise<SessionSummary> {
        return callBackendService(this?.waveEnv, "aisessions", "NoteAndTags", Array.from(arguments))
    }

    // rename an AI session tag globally
    // @returns AI session tag rename result
    RenameTag(request: AISessionsRenameTagRequest): Promise<AISessionsRenameTagResponse> {
        return callBackendService(this?.waveEnv, "aisessions", "RenameTag", Array.from(arguments))
    }

    // validate and resolve the runtime context for restoring an AI session
    // @returns validated AI session restore context
    RestoreContext(request: AISessionsRestoreContextRequest): Promise<AISessionsRestoreContextResponse> {
        return callBackendService(this?.waveEnv, "aisessions", "RestoreContext", Array.from(arguments))
    }

    // stat a local AI session file without loading messages
    // @returns AI session file stat
    Stat(request: AISessionsStatRequest): Promise<AISessionsStatResponse> {
        return callBackendService(this?.waveEnv, "aisessions", "Stat", Array.from(arguments))
    }

    // load a local AI session summary without loading messages
    // @returns AI session summary
    Summary(request: AISessionsSummaryRequest): Promise<SessionSummary> {
        return callBackendService(this?.waveEnv, "aisessions", "Summary", Array.from(arguments))
    }

    // list AI session tags
    // @returns AI session tags
    Tags(request: AISessionsTagsRequest): Promise<AISessionsTagsResponse> {
        return callBackendService(this?.waveEnv, "aisessions", "Tags", Array.from(arguments))
    }

    // set a local AI session title override
    // @returns updated AI session summary
    Title(id: string, title: string): Promise<SessionSummary> {
        return callBackendService(this?.waveEnv, "aisessions", "Title", Array.from(arguments))
    }

    // load latest user messages for a local AI session outline
    // @returns AI session user outline
    UserOutline(request: AISessionsUserOutlineRequest): Promise<AISessionsUserOutlineResponse> {
        return callBackendService(this?.waveEnv, "aisessions", "UserOutline", Array.from(arguments))
    }
}

export const AISessionsService = new AISessionsServiceType();

// blockservice.BlockService (block)
export class BlockServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // check agent status hook installation status
    // @returns agent status hook installation status
    CheckAgentStatusHooks(target: string): Promise<HookStatusResult> {
        return callBackendService(this?.waveEnv, "block", "CheckAgentStatusHooks", Array.from(arguments))
    }

    // queue a layout action to cleanup orphaned blocks in the tab
    // @returns object updates
    CleanupOrphanedBlocks(tabId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "CleanupOrphanedBlocks", Array.from(arguments))
    }

    // get canonical agent status for a block
    // @returns agent status
    GetAgentStatus(blockId: string): Promise<AgentStatus> {
        return callBackendService(this?.waveEnv, "block", "GetAgentStatus", Array.from(arguments))
    }
    GetControllerStatus(arg2: string): Promise<BlockControllerRuntimeStatus> {
        return callBackendService(this?.waveEnv, "block", "GetControllerStatus", Array.from(arguments))
    }

    // get a redacted diagnostic snapshot for one isolated agent vendor
    // @returns redacted vendor isolation status
    GetVendorIsolationStatus(apptype: string, vendorid: string): Promise<VendorIsolationStatus> {
        return callBackendService(this?.waveEnv, "block", "GetVendorIsolationStatus", Array.from(arguments))
    }

    // install agent status hooks after explicit user consent
    // @returns agent status hook installation results
    InstallAgentStatusHooks(target: string): Promise<HookInstallResult[]> {
        return callBackendService(this?.waveEnv, "block", "InstallAgentStatusHooks", Array.from(arguments))
    }

    // release canonical agent status source for a block
    // @returns agent status
    ReleaseAgentStatus(blockId: string, source: string, seq: number): Promise<AgentStatus> {
        return callBackendService(this?.waveEnv, "block", "ReleaseAgentStatus", Array.from(arguments))
    }

    // report canonical agent status for a block
    // @returns agent status
    ReportAgentStatus(report: AgentStatusReport): Promise<AgentStatus> {
        return callBackendService(this?.waveEnv, "block", "ReportAgentStatus", Array.from(arguments))
    }

    // save the terminal state to a blockfile
    SaveTerminalState(blockId: string, state: string, stateType: string, ptyOffset: number, termSize: TermSize): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "SaveTerminalState", Array.from(arguments))
    }
}

export const BlockService = new BlockServiceType();

// clientservice.ClientService (client)
export class ClientServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns object updates
    AgreeTos(): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "AgreeTos", Array.from(arguments))
    }
    FindCommand(arg2: string): Promise<string> {
        return callBackendService(this?.waveEnv, "client", "FindCommand", Array.from(arguments))
    }
    FindCommandForConnection(arg2: string, arg3: string, arg4: string): Promise<string> {
        return callBackendService(this?.waveEnv, "client", "FindCommandForConnection", Array.from(arguments))
    }
    FocusWindow(arg2: string): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "FocusWindow", Array.from(arguments))
    }
    GetAllConnStatus(): Promise<ConnStatus[]> {
        return callBackendService(this?.waveEnv, "client", "GetAllConnStatus", Array.from(arguments))
    }
    GetClientData(): Promise<Client> {
        return callBackendService(this?.waveEnv, "client", "GetClientData", Array.from(arguments))
    }
    GetTab(arg1: string): Promise<Tab> {
        return callBackendService(this?.waveEnv, "client", "GetTab", Array.from(arguments))
    }
    TelemetryUpdate(arg2: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "TelemetryUpdate", Array.from(arguments))
    }
}

export const ClientService = new ClientServiceType();

// commontextservice.CommonTextService (commontext)
export class CommonTextServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // get a common text item by id
    // @returns common text item
    Get(request: CommonTextGetRequest): Promise<CommonTextGetResponse> {
        return callBackendService(this?.waveEnv, "commontext", "Get", Array.from(arguments))
    }

    // list common text items
    // @returns common text items
    List(request: CommonTextListRequest): Promise<CommonTextListResponse> {
        return callBackendService(this?.waveEnv, "commontext", "List", Array.from(arguments))
    }

    // rename a common text tag globally
    // @returns common text tag rename result
    RenameTag(request: CommonTextRenameTagRequest): Promise<CommonTextRenameTagResponse> {
        return callBackendService(this?.waveEnv, "commontext", "RenameTag", Array.from(arguments))
    }

    // list common text tags
    // @returns common text tags
    Tags(request: CommonTextListRequest): Promise<CommonTextTagsResponse> {
        return callBackendService(this?.waveEnv, "commontext", "Tags", Array.from(arguments))
    }

    // update common text title, text, or tags
    // @returns updated common text item
    Update(request: CommonTextUpdateRequest): Promise<CommonTextItemType> {
        return callBackendService(this?.waveEnv, "commontext", "Update", Array.from(arguments))
    }
}

export const CommonTextService = new CommonTextServiceType();

// objectservice.ObjectService (object)
export class ObjectServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // copy an existing block to a newly created empty tab
    // @returns copy result (and object updates)
    CopyBlockToNewTab(blockId: string, tabNameBase: string): Promise<CopyBlockToNewTabResult> {
        return callBackendService(this?.waveEnv, "object", "CopyBlockToNewTab", Array.from(arguments))
    }

    // copy an existing block to another tab
    // @returns blockId (and object updates)
    CopyBlockToTab(blockId: string, targetTabId: string, activateTargetTab: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "object", "CopyBlockToTab", Array.from(arguments))
    }

    // @returns blockId (and object updates)
    CreateBlock(blockDef: BlockDef, rtOpts: RuntimeOpts): Promise<string> {
        return callBackendService(this?.waveEnv, "object", "CreateBlock", Array.from(arguments))
    }

    // create a new block in a newly created empty tab
    // @returns create result (and object updates)
    CreateBlockInNewTab(workspaceId: string, tabNameBase: string, blockDef: BlockDef, rtOpts: RuntimeOpts, magnified: boolean): Promise<CreateBlockInNewTabResult> {
        return callBackendService(this?.waveEnv, "object", "CreateBlockInNewTab", Array.from(arguments))
    }

    // create a new block in another tab
    // @returns blockId (and object updates)
    CreateBlockInTab(targetTabId: string, blockDef: BlockDef, rtOpts: RuntimeOpts, activateTargetTab: boolean, magnified: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "object", "CreateBlockInTab", Array.from(arguments))
    }

    // @returns object updates
    DeleteBlock(blockId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "DeleteBlock", Array.from(arguments))
    }

    // get wave object by oref
    GetObject(oref: string): Promise<WaveObj> {
        return callBackendService(this?.waveEnv, "object", "GetObject", Array.from(arguments))
    }

    // @returns objects
    GetObjects(orefs: string[]): Promise<WaveObj[]> {
        return callBackendService(this?.waveEnv, "object", "GetObjects", Array.from(arguments))
    }

    // move an existing block to a newly created empty tab
    // @returns tabId (and object updates)
    MoveBlockToNewTab(blockId: string, tabNameBase: string): Promise<string> {
        return callBackendService(this?.waveEnv, "object", "MoveBlockToNewTab", Array.from(arguments))
    }

    // move an existing block to another tab
    // @returns object updates
    MoveBlockToTab(blockId: string, targetTabId: string, activateTargetTab: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "MoveBlockToTab", Array.from(arguments))
    }

    // @returns object updates
    UpdateObject(waveObj: WaveObj, returnUpdates: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObject", Array.from(arguments))
    }

    // @returns object updates
    UpdateObjectMeta(oref: string, meta: MetaType): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObjectMeta", Array.from(arguments))
    }
}

export const ObjectService = new ObjectServiceType();

// userinputservice.UserInputService (userinput)
export class UserInputServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    SendUserInputResponse(arg1: UserInputResponse): Promise<void> {
        return callBackendService(this?.waveEnv, "userinput", "SendUserInputResponse", Array.from(arguments))
    }
}

export const UserInputService = new UserInputServiceType();

// windowservice.WindowService (window)
export class WindowServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    CloseWindow(windowId: string, fromElectron: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "window", "CloseWindow", Array.from(arguments))
    }
    CreateWindow(winSize: WinSize, workspaceId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "CreateWindow", Array.from(arguments))
    }
    GetWindow(windowId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "GetWindow", Array.from(arguments))
    }

    // set window position and size
    // @returns object updates
    SetWindowPosAndSize(windowId: string, pos: Point, size: WinSize): Promise<void> {
        return callBackendService(this?.waveEnv, "window", "SetWindowPosAndSize", Array.from(arguments))
    }
    SwitchWorkspace(windowId: string, workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "window", "SwitchWorkspace", Array.from(arguments))
    }
}

export const WindowService = new WindowServiceType();

// workspaceservice.WorkspaceService (workspace)
export class WorkspaceServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns CloseTabRtn (and object updates)
    CloseTab(workspaceId: string, tabId: string, fromElectron: boolean): Promise<CloseTabRtnType> {
        return callBackendService(this?.waveEnv, "workspace", "CloseTab", Array.from(arguments))
    }

    // create a new empty tab
    // @returns tabId (and object updates)
    CreateEmptyTab(workspaceId: string, tabName: string, activateTab: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateEmptyTab", Array.from(arguments))
    }

    // @returns tabId (and object updates)
    CreateTab(workspaceId: string, tabName: string, activateTab: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateTab", Array.from(arguments))
    }

    // @returns workspaceId
    CreateWorkspace(name: string, icon: string, color: string, applyDefaults: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateWorkspace", Array.from(arguments))
    }

    // @returns object updates
    DeleteWorkspace(workspaceId: string): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "DeleteWorkspace", Array.from(arguments))
    }

    // @returns colors
    GetColors(): Promise<string[]> {
        return callBackendService(this?.waveEnv, "workspace", "GetColors", Array.from(arguments))
    }

    // @returns icons
    GetIcons(): Promise<string[]> {
        return callBackendService(this?.waveEnv, "workspace", "GetIcons", Array.from(arguments))
    }

    // @returns workspace
    GetWorkspace(workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "workspace", "GetWorkspace", Array.from(arguments))
    }
    ListWorkspaces(): Promise<WorkspaceListEntry[]> {
        return callBackendService(this?.waveEnv, "workspace", "ListWorkspaces", Array.from(arguments))
    }

    // @returns object updates
    SetActiveTab(workspaceId: string, tabId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "workspace", "SetActiveTab", Array.from(arguments))
    }

    // @returns object updates
    UpdateWorkspace(workspaceId: string, name: string, icon: string, color: string, applyDefaults: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "workspace", "UpdateWorkspace", Array.from(arguments))
    }
}

export const WorkspaceService = new WorkspaceServiceType();

export const AllServiceTypes = {
    "aisessions": AISessionsServiceType,
    "block": BlockServiceType,
    "client": ClientServiceType,
    "commontext": CommonTextServiceType,
    "object": ObjectServiceType,
    "userinput": UserInputServiceType,
    "window": WindowServiceType,
    "workspace": WorkspaceServiceType,
};

export const AllServiceImpls = {
    "aisessions": AISessionsService,
    "block": BlockService,
    "client": ClientService,
    "commontext": CommonTextService,
    "object": ObjectService,
    "userinput": UserInputService,
    "window": WindowService,
    "workspace": WorkspaceService,
};
