// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

import { RpcApi } from "@/app/store/wshclientapi";
import { TabRpcClient } from "@/app/store/wshrpcutil";
import type { AgentStatus } from "./agent-status-types";

// WaveNotificationOptions is a `declare global` type from frontend/types/gotypes.d.ts
// (regenerated by `task generate` after the Go struct gains agentkind/agentblockid/
// agentprovider), so no explicit import is needed. Until `task generate` runs, tsc will
// flag those fields as unknown on the opts literal — that's expected and resolves at the
// `task generate` step at the end of this change-set.

// FE-side dispatcher for OS-level agent status notifications. Single public entry —
// fireAgentOsNotification(next, prev) — called from the transition observer in
// agent-status-done-ack-store.ts. Everything else (settings read, focused-window suppression,
// rate-limit, Notification instance) lives in the main process (emain/os-notify.ts); the FE
// only describes *what* transitioned and where.
//
// Design notes:
//  - FE does NOT read agentstatus:* settings. The main process does, so a setting change takes
//    effect on the very next call without a renderer round-trip.
//  - "prev" is passed in by the caller (the transition observer, which already tracks it per
//    blockId) so this module stays stateless and trivially unit-testable.
//  - We only fire on real transitions (prev-state → new-state), not on every status event.
//    Wobble inside the same band (working → working) is intentionally a no-op; that's the job of
//    decideNotifyKind, which is what makes the unit test meaningful.
//  - The RPC payload is shaped by the agentkind/agentblockid/agentprovider fields on
//    WaveNotificationOptions; the Go struct tags are omitempty so plain updater/CLI notify
//    calls (which leave those fields empty) are unaffected.

export type AgentOsNotifyKind = "done" | "blocked";

/**
 * Pure transition classifier. Returns the notification kind (if any) that should fire for a
 * given prev → next transition, or null if no notification is warranted.
 *
 * Rules (POC):
 *  - "done":    non-idle (working-class) → idle   (a real completion turning the indicator green)
 *  - "blocked": * → blocked                         (agent paused waiting on input/approval/shell)
 *
 * Non-events:
 *  - Same state prev == next (wobble inside the same band).
 *  - "stale"/"unknown" target state — those are noise-class states.
 *  - prev == null on a "done": cannot claim a completion without having observed a prior working
 *    state. Once we've observed at least one event for this block, the next working→idle will
 *    qualify normally.
 */
export function decideNotifyKind(next: AgentStatus | null, prev: AgentStatus | null): AgentOsNotifyKind | null {
    if (next == null) return null;

    // Noise-class target states never fire.
    if (next.state === "stale" || next.state === "unknown") return null;

    if (next.state === "blocked") {
        // No transition: a blocked→blocked burst (e.g. multiple approval-required events firing
        // back-to-back) should not re-toast. The main-process rate-limit is the backstop, but
        // the classifier drops the boring case first so observers don't even dispatch.
        if (prev != null && prev.state === "blocked") return null;
        return "blocked";
    }

    if (next.state === "idle") {
        if (prev == null) return null;
        // Only fire "done" when prev was a real working-class state — NOT when prev itself was
        // blocked (blocked → idle is the user resuming; they just touched it, no toast needed),
        // and not when prev was already idle (wobble, the green dot didn't freshly light).
        if (prev.state === "idle" || prev.state === "blocked") return null;
        if (prev.state === "stale" || prev.state === "unknown") return null;
        return "done";
    }

    return null;
}

/**
 * Public entry the transition observer calls. Suppresses entirely if decideNotifyKind returns
 * null, or if the RPC can't be dispatched (no active tab client yet at startup) — agent UX
 * must NEVER depend on notifications. All failures are swallowed: this runs on the agent-status
 * event path and must not crash the event handler.
 */
export function fireAgentOsNotification(next: AgentStatus, prev: AgentStatus | null): void {
    try {
        const kind = decideNotifyKind(next, prev);
        if (kind == null) return;

        const opts = {
            agentkind: kind,
            agentblockid: next.blockId,
            agentprovider: next.provider,
            // Body left empty — the main process derives the default copy from provider/kind.
            // Caller may extend later with a phase-aware message (e.g. "waiting for approval").
        } as WaveNotificationOptions;

        // Fire-and-forget: if it fails (no client yet at startup, renderer being torn down),
        // we just log. We never throw into the observer path.
        //
        // Route must be "electron": without it the Go router sends the command to the
        // "wavesrv" (WshServer) route, which has no NotifyCommand handler, and the RPC
        // fails with `command not implemented "notify"` — silently, via the catch below.
        // This is the same routing the `wsh notify` CLI uses (cmd/wsh/cmd/wshcmd-notify.go)
        // and the FE bell path (termwrap.ts ElectronSystemBellCommand).
        RpcApi.NotifyCommand(TabRpcClient, opts, { route: "electron" }).catch((err) => {
            console.warn("[agent-status-notify] notify RPC failed", err);
        });
    } catch (err) {
        // Defensive: any failure here must not crash the agent-status event handler.
        console.warn("[agent-status-notify] fireAgentOsNotification error", err);
    }
}
